services:
  - type: web
    name: mdsaad-proxy-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node api-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: WEATHERAPI_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://mdsaad-proxy-api.onrender.com
    healthCheckPath: /health
    numInstances: 1
    maxSurge: 0
    maxUnavailable: 0
    autoDeploy: true